"""Every path referenced by the README, the configs and slurm/ must resolve.

A directory rename previously broke the documented smoke command while every
literal-path check still passed, because the path was assembled from a shell
variable. This check therefore expands `VAR="${VAR:-default}"` before resolving.

Run: PYTHONPATH=src python -m unittest discover -s tests
"""
from __future__ import annotations

import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# repo-relative paths that denote shipped files
PATH_RE = re.compile(r"(?<![\w/])((?:src|slurm|scripts|configs|inputs|env|tests|patches|docs)/[\w./-]+)")
# VAR="${VAR:-default}" / VAR="default"
ASSIGN_RE = re.compile(r'^(\w+)=(?:"?\$\{\1:-([^}"]*)\}"?|"([^"$]*)")', re.M)


def _expand(text: str) -> str:
    """Substitute shell variables with their in-file default values."""
    defaults = {m.group(1): (m.group(2) or m.group(3) or "") for m in ASSIGN_RE.finditer(text)}
    for _ in range(3):  # resolve nested defaults
        for name, val in defaults.items():
            text = text.replace(f"${{{name}}}", val).replace(f"${name}", val)
    return text


def _referenced(path: Path) -> set[str]:
    raw = path.read_text(errors="replace")
    text = _expand(raw) if path.suffix == ".sh" else raw
    hits = set()
    for m in PATH_RE.finditer(text):
        p = m.group(1).rstrip(".,;:)")
        # skip run-time output paths and glob patterns
        if (p.startswith(("outputs/", "logs/")) or "*" in p
                or "YOUR_" in p or "your_" in p):
            continue
        hits.add(p)
    return hits


class RepoPathsResolve(unittest.TestCase):
    def _check(self, files):
        missing = []
        for f in files:
            for p in sorted(_referenced(f)):
                if not (ROOT / p).exists():
                    missing.append(f"{f.relative_to(ROOT)} -> {p}")
        self.assertEqual(missing, [], "referenced paths do not exist:\n  " + "\n  ".join(missing))

    def test_readme(self):
        self._check([ROOT / "README.md"])

    def test_slurm_wrappers(self):
        self._check(sorted((ROOT / "slurm").glob("*.sh")))

    def test_scripts(self):
        self._check(sorted((ROOT / "scripts").glob("*.sh")))

    def test_configs(self):
        self._check(sorted((ROOT / "configs").glob("*.yaml")))

    def test_src_docstrings_and_generated_commands(self):
        """Paths in src/ must resolve, including those in generated commands.

        Module docstrings, --help text and the sbatch body generated by
        param_sweep all reference repository paths, and a stale reference there
        is a functional defect rather than a documentation one.
        """
        self._check(sorted((ROOT / "src").glob("*.py")))

    def test_wrappers_use_src_entrypoint(self):
        """Wrappers must invoke src/, not a stale sibling directory."""
        for f in sorted((ROOT / "slurm").glob("*.sh")):
            text = _expand(f.read_text(errors="replace"))
            for m in re.finditer(r"([\w./${}-]*)switch_pipeline[\w]*\.py", text):
                self.assertTrue(
                    m.group(0).startswith("src/"),
                    f"{f.name} invokes {m.group(0)!r}; entry points live in src/")


if __name__ == "__main__":
    unittest.main()
